### PR TITLE
Add support for microseconds for datetime, timestamp and time

### PR DESCRIPTION
**Pull request by laurocaetano**
Just updated with microseconds support for Date, Timestamp and Time.

### CODE REVIEW

**Comment by laurocaetano** [comment]
Updated. Now it covers Datetime, Timestamp and Datetime

**Comment by laurocaetano** [comment]
It seems there is an issue with the MySQL version here. I'll take a look and fix.

**Comment by josevalim** [comment]
For some context, Ecto uses a 4-item tuple for times now.

**Comment by laurocaetano** [comment]
Just updated the tests here.
It was using fractional seconds when the column was defined, but it only works on MySQL 5.7 +

Reference: http://dev.mysql.com/doc/refman/5.7/en/fractional-seconds.html

**Comment by liveforeverx** [comment]
Thanks!!

**Pull request merged**
